### ISSUE TITLE
Unable to install dependencies using Carthage

### ISSUE THREAD

**Issue by martinpilch** [Sage-Bionetworks/BridgeApp-Apple-SDK#189]
Hi, this is the very first issue here so I hope it finds you 😃 

I'm trying to install dependencies using Carthage to test example app. When running `carthage update` from the root folder I get following error (copy-pasting last couple of lines):

```
Build settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphonesimulator13.5

note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
warning: MobileCoreServices has been renamed. Use CoreServices instead. (in target 'BridgeSDK' from project 'BridgeSDK')
error: Building for iOS Simulator, but the linked library 'openssl.a' was built for iOS. (in target 'BridgeSDK' from project 'BridgeSDK')

** BUILD FAILED **
```

Am I doing it wrong?

**Comment by martinpilch** [comment]
### UPDATE
I managed to install dependencies using following command:
`carthage update --platform iOS --use-submodules --no-use-binaries --no-build`

When I try to compile the example app I get couple of errors about various classes not conforming to DocumentableInterface. For example:

```
Type 'ColorMappingSerializer' does not conform to protocol 'DocumentableInterface'
Type 'ImageThemeSerializer' does not conform to protocol 'DocumentableInterface'
Type 'AsyncActionConfigurationSerializer' does not conform to protocol 'DocumentableInterface'
Type 'InputItemSerializer' does not conform to protocol 'DocumentableInterface'
Type 'AnswerTypeSerializer' does not conform to protocol 'DocumentableInterface'
Type 'ButtonActionSerializer' does not conform to protocol 'DocumentableInterface'
Type 'StepSerializer' does not conform to protocol 'DocumentableInterface'
...
```

**Comment by syoung-smallwisdom** [comment]
@martinpilch 

Hi there, this is my fault. Unfortunately, I had the SwiftPM dependencies set up incorrectly so that the JsonModel library that these frameworks depend upon is pointing to master and not a tagged version. https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/188 fixes this and I will deploy ASAP once everything is fixed.

**Comment by syoung-smallwisdom** [comment]
@martinpilch 
v4.1.25 Should build successfully with latest version of SageResearch.

**Comment by martinpilch** [comment]
thanks a lot for your time! I'm able to build the example app now. Closing the issue
